# Generated by Django 5.1 on 2024-11-11 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_wasterequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WasteRequest',
        ),
    ]
