# Generated by Django 5.1 on 2024-11-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0007_remove_userprofile_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('driver', 'Driver')], default='user', max_length=20),
        ),
    ]
