# Generated by Django 5.1 on 2024-11-11 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wasteapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wasterequest',
            old_name='collection_loaction',
            new_name='collection_location',
        ),
    ]
