# Generated by Django 5.1.2 on 2024-11-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteapp', '0003_alter_wasterequest_collection_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasterequest',
            name='collection_location',
            field=models.CharField(max_length=255),
        ),
    ]
