# Generated by Django 5.1 on 2025-03-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteapp', '0006_wasterequest_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterequest',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
