# Generated by Django 5.1 on 2025-03-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteapp', '0009_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location_link', models.URLField(blank=True, help_text='Optional link for more info or registration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WasteTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('tag', models.CharField(blank=True, help_text='Optional tag to group or filter tips', max_length=50)),
                ('youtube_link', models.URLField(blank=True, help_text='Optional YouTube link for related video', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
